name: Release Python SDK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Authenticate to GitHub for private .whl access
        run: |
          echo "machine github.com" >> ~/.netrc
          echo "login ${{ secrets.GH_USERNAME }}" >> ~/.netrc
          echo "password ${{ secrets.GH_PAT }}" >> ~/.netrc

      - name: Install dependencies
        run: poetry install

      - name: Build SDK
        run: poetry build

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
